version: "2"
services:
  config-server:
    image: httpd:alpine
    ports:
      - "8000:80"
    volumes:
      - ${DIR}/config-server:/usr/local/apache2/htdocs:ro
  mysql:
    image: mysql:latest
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=666666
      - MYSQL_DATABASE=vertx_blueprint
  keycloak-server:
    image: jboss/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
  redis:
    image: redis:latest
    expose:
      - "6379"
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    command: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
  logstash:
    image: logstash
    ports:
      - "12201:12201/udp"
    command: -e 'input { gelf { host => "0.0.0.0" port => 12201 } }
              output { elasticsearch { hosts => ["elasticsearch"] } }'
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  kibana:
    image: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch
      - logstash
    depends_on:
      - logstash

  sample-microservice:
    image: vertx-blueprint/sample-microservice
    links:
      - config-server
      - redis
      - logstash
    depends_on:
      - config-server
      - redis
      - logstash
    expose:
      - "8086"

  cache-infrastructure:
    image: vertx-blueprint/cache-infrastructure
    links:
      - redis
      - logstash
    depends_on:
      - redis
      - logstash

  monitor-dashboard:
    image: vertx-blueprint/monitor-dashboard
    ports:
      - "9100:9100"
    links:
      - logstash
    depends_on:
      - logstash

  api-gateway:
    image: vertx-blueprint/api-gateway
    ports:
      - "8787:8787"
    environment:
      - JAVA_OPTS="-Xms128m -Xmx256m"
    links:
      - keycloak-server
      - logstash
    extra_hosts:
      - "dockernet:${EXTERNAL_IP}"
